# -*- coding: utf-8 -*-
"""Livestock data for the Urban GreenWorks Almanac.

Cleaned from the UGW egg log + chicken purchase/sourcing sheets (2026).
Egg-type strings like '[3 Bwn; 2 EE]' are parsed into brown vs Easter-egger/blue.
"""

EGGS = [{'date': '2026-01-12',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-14',
  'flock': 'F1',
  'total': 4,
  'brown': 2,
  'other': 2,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-16',
  'flock': 'F1',
  'total': 4,
  'brown': 3,
  'other': 1,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-18',
  'flock': 'F1',
  'total': 4,
  'brown': 2,
  'other': 2,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-20',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-22',
  'flock': 'F1',
  'total': 3,
  'brown': 1,
  'other': 2,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-25',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-29',
  'flock': 'F1',
  'total': 5,
  'brown': 3,
  'other': 2,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-01-31',
  'flock': 'F1',
  'total': 6,
  'brown': 4,
  'other': 2,
  'feed': 'Henhouse Reserve with Pellets',
  'staff': ''},
 {'date': '2026-02-02', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-03', 'flock': 'F1', 'total': 5, 'brown': 3, 'other': 2, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-05', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-06', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-08', 'flock': 'F1', 'total': 5, 'brown': 3, 'other': 2, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-09', 'flock': 'F1', 'total': 2, 'brown': 1, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-11', 'flock': 'F1', 'total': 4, 'brown': 3, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-12', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-13', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-15', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-16', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-19', 'flock': 'F1', 'total': 5, 'brown': 3, 'other': 2, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-20', 'flock': 'F1', 'total': 3, 'brown': 2, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-22', 'flock': 'F1', 'total': 6, 'brown': 4, 'other': 2, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-24', 'flock': 'F1', 'total': 1, 'brown': 0, 'other': 1, 'feed': '', 'staff': 'RH'},
 {'date': '2026-02-28',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-01',
  'flock': 'F1',
  'total': 5,
  'brown': 3,
  'other': 2,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-02',
  'flock': 'F1',
  'total': 2,
  'brown': 1,
  'other': 1,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-03',
  'flock': 'F1',
  'total': 1,
  'brown': 0,
  'other': 1,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-04',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-06',
  'flock': 'F1',
  'total': 5,
  'brown': 3,
  'other': 2,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-07',
  'flock': 'F1',
  'total': 2,
  'brown': 1,
  'other': 1,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-08',
  'flock': 'F1',
  'total': 1,
  'brown': 0,
  'other': 1,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-09',
  'flock': 'F1',
  'total': 2,
  'brown': 1,
  'other': 1,
  'feed': 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
  'staff': ''},
 {'date': '2026-03-12',
  'flock': 'F1',
  'total': 4,
  'brown': 2,
  'other': 2,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-14', 'flock': 'F1', 'total': 3, 'brown': 0, 'other': 0, 'feed': '', 'staff': ''},
 {'date': '2026-03-15',
  'flock': 'F1',
  'total': 1,
  'brown': 0,
  'other': 1,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-16',
  'flock': 'F1',
  'total': 2,
  'brown': 1,
  'other': 1,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-17',
  'flock': 'F1',
  'total': 2,
  'brown': 1,
  'other': 1,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-19',
  'flock': 'F1',
  'total': 2,
  'brown': 1,
  'other': 1,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-21',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-24',
  'flock': 'F1',
  'total': 3,
  'brown': 1,
  'other': 2,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-26',
  'flock': 'F1',
  'total': 5,
  'brown': 4,
  'other': 1,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-03-31',
  'flock': 'F1',
  'total': 4,
  'brown': 2,
  'other': 2,
  'feed': 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
  'staff': ''},
 {'date': '2026-04-02',
  'flock': 'F1',
  'total': 6,
  'brown': 4,
  'other': 2,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-05',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-06',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-08',
  'flock': 'F1',
  'total': 4,
  'brown': 2,
  'other': 2,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-09',
  'flock': 'F1',
  'total': 5,
  'brown': 3,
  'other': 2,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-10',
  'flock': 'F1',
  'total': 6,
  'brown': 4,
  'other': 2,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-12',
  'flock': 'F1',
  'total': 6,
  'brown': 4,
  'other': 2,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-16',
  'flock': 'F1',
  'total': 12,
  'brown': 9,
  'other': 3,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-18',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-19',
  'flock': 'F1',
  'total': 6,
  'brown': 3,
  'other': 3,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-22',
  'flock': 'F1',
  'total': 4,
  'brown': 3,
  'other': 1,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-24',
  'flock': 'F1',
  'total': 5,
  'brown': 2,
  'other': 3,
  'feed': 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'staff': ''},
 {'date': '2026-04-26',
  'flock': 'F1',
  'total': 9,
  'brown': 6,
  'other': 3,
  'feed': 'Solid Woms+ Kalm Chickenhouse Reserve 18% Grain (30lbs) + Kalm 5 - Grain Prem Scratch Grain ( '
          '50lbs)',
  'staff': ''},
 {'date': '2026-04-28',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Solid Woms+ Kalm Chickenhouse Reserve 18% Grain (30lbs) + Kalm 5 - Grain Prem Scratch Grain ( '
          '50lbs)',
  'staff': ''},
 {'date': '2026-04-30',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Solid Woms+ Kalm Chickenhouse Reserve 18% Grain (30lbs) + Kalm 5 - Grain Prem Scratch Grain ( '
          '50lbs)',
  'staff': ''},
 {'date': '2026-05-01',
  'flock': 'F1',
  'total': 3,
  'brown': 2,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-02',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-04',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-05',
  'flock': 'F1',
  'total': 8,
  'brown': 6,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-06',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-07',
  'flock': 'F1',
  'total': 8,
  'brown': 6,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-08',
  'flock': 'F1',
  'total': 8,
  'brown': 6,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-10',
  'flock': 'F1',
  'total': 11,
  'brown': 9,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-11',
  'flock': 'F1',
  'total': 8,
  'brown': 6,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-12',
  'flock': 'F1',
  'total': 4,
  'brown': 3,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'RH'},
 {'date': '2026-05-14',
  'flock': 'F1',
  'total': 14,
  'brown': 12,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-15',
  'flock': 'F1',
  'total': 6,
  'brown': 4,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-16',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-17',
  'flock': 'F1',
  'total': 9,
  'brown': 8,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-19',
  'flock': 'F1',
  'total': 9,
  'brown': 7,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-20',
  'flock': 'F1',
  'total': 9,
  'brown': 7,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-21',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-22',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-23',
  'flock': 'F1',
  'total': 8,
  'brown': 6,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-24',
  'flock': 'F1',
  'total': 2,
  'brown': 2,
  'other': 0,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-25',
  'flock': 'F1',
  'total': 14,
  'brown': 12,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-26',
  'flock': 'F1',
  'total': 9,
  'brown': 7,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-27',
  'flock': 'F1',
  'total': 6,
  'brown': 4,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-29',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-30',
  'flock': 'F1',
  'total': 8,
  'brown': 6,
  'other': 2,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-05-31',
  'flock': 'F1',
  'total': 9,
  'brown': 8,
  'other': 1,
  'feed': 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
  'staff': 'NL'},
 {'date': '2026-06-01',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-02',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-03',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-04',
  'flock': 'F1',
  'total': 9,
  'brown': 8,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-05',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-06',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-09',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-10',
  'flock': 'F1',
  'total': 9,
  'brown': 7,
  'other': 2,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-11',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-12',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-13',
  'flock': 'F1',
  'total': 8,
  'brown': 6,
  'other': 2,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-14',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-15',
  'flock': 'F1',
  'total': 9,
  'brown': 7,
  'other': 2,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-16',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-17',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
  'staff': ''},
 {'date': '2026-06-18',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-19',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': 'NL'},
 {'date': '2026-06-20',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-21',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-22',
  'flock': 'F1',
  'total': 7,
  'brown': 7,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': 'NL'},
 {'date': '2026-06-23',
  'flock': 'F1',
  'total': 7,
  'brown': 7,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-24',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-25',
  'flock': 'F1',
  'total': 7,
  'brown': 7,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-26',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-27',
  'flock': 'F1',
  'total': 7,
  'brown': 7,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-28',
  'flock': 'F1',
  'total': 7,
  'brown': 7,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-06-30',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': 'NL'},
 {'date': '2026-07-01',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-02',
  'flock': 'F1',
  'total': 5,
  'brown': 5,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-03',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-04',
  'flock': 'F1',
  'total': 8,
  'brown': 7,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-05',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-06',
  'flock': 'F1',
  'total': 7,
  'brown': 6,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-07',
  'flock': 'F1',
  'total': 9,
  'brown': 7,
  'other': 2,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-08',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-09',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-10',
  'flock': 'F1',
  'total': 10,
  'brown': 8,
  'other': 2,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-11',
  'flock': 'F1',
  'total': 6,
  'brown': 5,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-12',
  'flock': 'F1',
  'total': 7,
  'brown': 5,
  'other': 2,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-13',
  'flock': 'F1',
  'total': 9,
  'brown': 7,
  'other': 2,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-14',
  'flock': 'F1',
  'total': 4,
  'brown': 4,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-15',
  'flock': 'F1',
  'total': 9,
  'brown': 8,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-16',
  'flock': 'F1',
  'total': 6,
  'brown': 6,
  'other': 0,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''},
 {'date': '2026-07-17',
  'flock': 'F1',
  'total': 9,
  'brown': 8,
  'other': 1,
  'feed': 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms',
  'staff': ''}]

EGGS_MONTHLY = [{'month': '2026-01', 'label': 'Jan 2026', 'total': 38, 'brown': 24, 'other': 14, 'avg_per_day': 4.2},
 {'month': '2026-02', 'label': 'Feb 2026', 'total': 55, 'brown': 35, 'other': 20, 'avg_per_day': 3.4},
 {'month': '2026-03', 'label': 'Mar 2026', 'total': 50, 'brown': 25, 'other': 22, 'avg_per_day': 2.8},
 {'month': '2026-04', 'label': 'Apr 2026', 'total': 85, 'brown': 57, 'other': 28, 'avg_per_day': 5.7},
 {'month': '2026-05', 'label': 'May 2026', 'total': 201, 'brown': 163, 'other': 38, 'avg_per_day': 7.7},
 {'month': '2026-06', 'label': 'Jun 2026', 'total': 195, 'brown': 176, 'other': 19, 'avg_per_day': 7.2},
 {'month': '2026-07', 'label': 'Jul 2026', 'total': 123, 'brown': 105, 'other': 18, 'avg_per_day': 7.2}]

FEEDS = ['Henhouse Reserve with Pellets',
 'Kalm Layer 16% Crumble + Kalm Henhouse Reserve layer grain 17 %',
 'Sheel & Bone Builder ( Purdue) + Viggie Mix + Starch grain',
 'Kalm Chickenhouse Reserve 18% Grain (30lbs) +  Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
 'Solid Woms+ Kalm Chickenhouse Reserve 18% Grain (30lbs) + Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
 'Henhouse Reserve LB + Vibrant Life Dried Soldier Worm Treats',
 'Healthy Harvest 16% Layer Pellets for Chickens + Henhouse Reserve Love Bug',
 'Kalm Bach Henhouse Reserve with Mini Pellets (30lbs) + Larve Worms']

LIVESTOCK_COSTS = [{'date': '2026-06-23',
  'item': 'Badia Crushed Red Pepper, 4.5 oz Bottle',
  'cost': 4.87,
  'store': 'Walmart',
  'flock': 'F2'},
 {'date': '2026-06-29',
  'item': 'Healthy Harvest 16% Crumble ( 40lbs)',
  'cost': 13.62,
  'store': 'Walmart',
  'flock': 'F2'},
 {'date': 'March 12th, 2026',
  'item': 'Kalm Layer 16% Crumble ( 50lbs) x 2',
  'cost': 19.69,
  'store': "Robbie's Feed & Supply",
  'flock': 'F1'},
 {'date': '', 'item': 'Scratch 3- Grain', 'cost': 18.99, 'store': "Robbie's Feed & Supply", 'flock': 'F1'},
 {'date': 'April 2nd, 2026',
  'item': 'Kalm Chickenhouse Reserve 18% Grain (30lbs)',
  'cost': 20.65,
  'store': "Robbie's Feed & Supply",
  'flock': 'F1'},
 {'date': 'April 5th, 2026', 'item': 'Pet Bedding x 2', 'cost': 7.98, 'store': 'Walmart', 'flock': 'F1'},
 {'date': 'April 16th, 2026',
  'item': 'Kalm 5 - Grain Prem Scratch Grain ( 50lbs)',
  'cost': 19.95,
  'store': "Robbie's Feed & Supply",
  'flock': 'F1'},
 {'date': 'April 24th, 2026', 'item': 'Pet Bedding x 2', 'cost': 7.98, 'store': 'Walmart', 'flock': 'F1'},
 {'date': 'April 25th, 2026', 'item': 'Pet Bedding x 4', 'cost': 3.98, 'store': 'Walmart', 'flock': 'F1'},
 {'date': 'May 18th ,2026', 'item': 'Solid Worms', 'cost': 8.88, 'store': 'Walmart', 'flock': 'F1'},
 {'date': 'May 21st , 2026',
  'item': 'Kalm Chickenhouse Reserve 18% Grain (30lbs)  with Mini Pellets',
  'cost': 20.65,
  'store': "Robbie's Feed & Supply",
  'flock': 'F1'},
 {'date': 'June 23rd, 2026',
  'item': 'Badia Crushed Red Pepper, 4.5 oz Bottle x2',
  'cost': 4.87,
  'store': 'Walmart',
  'flock': 'F1'},
 {'date': '',
  'item': 'Pecking Order ( Mealworm and Sunflower Blend) 3 lbs',
  'cost': 5.96,
  'store': 'Walmart',
  'flock': 'F1'}]

CHICKEN_SOURCING = [{'product': 'Organic Apple Cider Vinegar',
  'brand': 'White House, Braggs',
  'where': 'Walmart',
  'notes': 'Cheapest at Walmart, White House Brand'},
 {'product': 'Scratch and Peck Dried Herbs Supplement for Chickens and Ducks - 10 oz Bag - Natural, Aromatic '
             'Nesting Box Herbs - Certi',
  'brand': 'Scratch and Peck Feeds',
  'where': 'Amazon',
  'notes': 'Mix in small amount with feed- good for immune health'},
 {'product': 'Pine Shavings Bedding',
  'brand': 'Stall Master- large and medium flake',
  'where': "Robbie's Feed",
  'notes': "Address of Robbie's Feed and Supply:   22390 SW 177th Ave, Miami, FL 33170"},
 {'product': '"New Country Organics soy-free, Corn-free layer,\r\n50 lb"',
  'brand': 'New Country Organics',
  'where': 'Margie Pikarsky',
  'notes': '"she buys in bulk and stores at her farm, we pick up small amounts as needed from her- give her '
           'atleast 2 weeks heads up when more food needs to be ordered\r\n'
           'Contact: 786-256-6657\r\n'
           'Address: 19000 SW 26'},
 {'product': '"New Country Organics Soy-free, Corn-free layer, with OGS, \r\n50 lb"',
  'brand': 'Verticarb Inc.',
  'where': 'Carl DiPiazza',
  'notes': 'Contains Organic Gut Solution (OGC) for protein absorption'},
 {'product': '"New Country Organics soy-free Chicken\r\nGrower/Broiler Feed, 40 lb bag"',
  'brand': 'New Country Organics',
  'where': 'Margie Pikarsky',
  'notes': ''},
 {'product': 'New Country Organics Corn-free soy-free starter feed, 40 lb',
  'brand': 'New Country Organics',
  'where': 'Margie Pikarsky',
  'notes': ''},
 {'product': 'Poultry Grit, 50lb bag',
  'brand': 'New Country Organics',
  'where': 'Margie Pikarsky',
  'notes': '"""\r\nGrit may not be totaly necessary given our soil is very rocky- discuss more with Margie"'},
 {'product': 'First Saturday Lime', 'brand': 'First Saturday Lime', 'where': '31', 'notes': ''},
 {'product': 'Diatmaceous Earth',
  'brand': 'PermaGuard Crawling Insect Control',
  'where': 'Amazon',
  'notes': 'For dust bath'},
 {'product': 'Misc Supplies (NOT needing QCS Approval)',
  'brand': 'N/A',
  'where': "Robbie's Feed",
  'notes': '"local supplier- see address here\r\n'
           'if you need to quickly get more waterers, food containers, etc- nothing that would be considered '
           'an ""input"" that would need prior approval"'},
 {'product': "Shell & Bone Builder 5 #'s",
  'brand': 'Perdue, Flock Leader',
  'where': 'Walmart',
  'notes': 'Calcium supplement for the chickens supports strong eggshells and bone health.'},
 {'product': 'Dried Solid Worm ( Treat for Chickens) 1 #',
  'brand': 'Vibrant Life',
  'where': 'Walmart',
  'notes': "This is given to the chickens as a treat;9' they love this stuff."},
 {'product': "Organic Henhouse Reserve ( Kalmbach) Organic; Soy Free and Corn Free 30 #'s",
  'brand': 'Kalmbach Feeds',
  'where': "Robbie's Feed",
  'notes': "This is the 1st choice for chicken feed, is a bit expensive, so it's not bought often."},
 {'product': "Henhouse Reserve Love Bug Edition 30 #'s",
  'brand': 'Kalmbach Feeds',
  'where': "Robbie's Feed",
  'notes': 'Cheapest at Walmart but can be bought on the Kalmbach official website.  Secondary choice for '
           'chicken feed'},
 {'product': "Henhouse Reserve with Crumbles  30 #'s",
  'brand': 'Kalmbach Feeds',
  'where': "Robbie's Feed",
  'notes': "Bought at Robbie's feed, but can be bought at the Kalmbach official website. Tertiary feed "
           'choice.'},
 {'product': "Henhouse Reserve with Mini Pellets 30 #'s",
  'brand': 'Kalmbach Feeds',
  'where': 'Walmart',
  'notes': 'Cheapest at Walmart, Quaternary feed choice.'},
 {'product': "Healthy Harvest medicated starter grower  5 #'s",
  'brand': 'Healthy Harvest',
  'where': 'Walmart',
  'notes': 'Cheapest at Walmart, this is feed if specifically for the second flock of chicks.'},
 {'product': 'Badia Crushed Red Pepper, 4.5 oz Bottle',
  'brand': 'Badia',
  'where': 'Walmart',
  'notes': "The Pepper Flakes , like the Vet Rx Drops, are good for the chickens' stomachs to prevent loose "
           'stool'},
 {'product': 'Pecking Order ( Mealworm and Sunflower Blend) 3 lbs',
  'brand': 'Pecking Order',
  'where': 'Walmart',
  'notes': ''},
 {'product': 'Healthy Harvest 16% Crumble ( 40lbs)',
  'brand': 'Healthy Harvest',
  'where': 'Walmart',
  'notes': ''}]

TOTAL_EGGS = 747
TOTAL_BROWN = 585
TOTAL_OTHER = 159
TOTAL_COST = 158.07
EGG_MIN = '2026-01-12'
EGG_MAX = '2026-07-17'
