# -*- coding: utf-8 -*-
"""Farm pesticide/biopesticide data for the Urban GreenWorks Almanac.

Cleaned from UGW.pesticide.application.log.23-26.xlsx (139 applications,
126 with clean dates spanning Mar 2023 - Jun 2026). Chemical health &
environmental cards are summarized from EPA + NPIC (NIH/EPA-cooperative)
primary sources; each card carries its citations in `sources`.
"""

CHEMICALS = [{'id': 'neem',
  'name': 'Neem Oil',
  'active': 'Azadirachtin + neem seed oil',
  'ptype': 'Insecticide / miticide',
  'origin': 'Botanical — neem tree seed',
  'omri': 'OMRI-listed',
  'targets': 'Aphids, whitefly, mites and other soft-bodied insects; mild fungal suppression',
  'health': 'Low acute toxicity to people; can slightly irritate the eyes and skin. Most of the '
            'oil is fatty acids and oils “commonly eaten in a normal diet” and FDA-recognized as '
            'safe, and no association with increased cancer risk has been found.',
  'environment': 'Azadirachtin breaks down quickly — soil half-life ~3–44 days, in water 48 min–4 '
                 'days, on leaves 1–2.5 days.',
  'pollinators': 'Pollinators are unlikely to be harmed because insects generally must eat treated '
                 'tissue to be affected; still avoid spraying open blooms.',
  'aquatic': 'Slightly to moderately toxic to fish and aquatic animals — keep out of waterways.',
  'caution': 'low',
  'sources': [{'label': 'NPIC — Neem Oil General Fact Sheet',
               'url': 'https://npic.orst.edu/factsheets/neemgen.html'}],
  'applications': 84},
 {'id': 'insecticidal_soap',
  'name': 'Insecticidal Soap (incl. Des-X)',
  'active': 'Potassium salts of fatty acids',
  'ptype': 'Contact insecticide',
  'origin': 'Fatty-acid salts (plant/mineral)',
  'omri': 'OMRI-listed',
  'targets': 'Aphids, whitefly, nymphs and soft-bodied pests — kills on direct contact while wet',
  'health': 'Low toxicity to humans; the soap salts are FDA ‘Generally Recognized as Safe’ and '
            'have been exempt from food-crop residue limits since 1982. Labels still warn it can '
            'irritate skin and cause temporary eye injury.',
  'environment': 'Breaks down readily with no soil persistence, but labels warn it ‘may be '
                 'hazardous to aquatic invertebrates’ — never apply directly to water.',
  'pollinators': 'Acts only on direct contact while wet, so residual risk to pollinators is low if '
                 'not sprayed on active foragers.',
  'aquatic': 'May harm aquatic invertebrates — avoid water and intertidal areas.',
  'caution': 'low',
  'sources': [{'label': 'EPA — Soap Salts Reregistration Eligibility (RED) Fact Sheet',
               'url': 'https://archive.epa.gov/pesticides/reregistration/web/pdf/4083fact.pdf'}],
  'applications': 128},
 {'id': 'bt',
  'name': 'Bacillus thuringiensis (Bt)',
  'active': 'Bt kurstaki / aizawai Cry proteins',
  'ptype': 'Biological insecticide',
  'origin': 'Naturally occurring soil bacterium',
  'omri': 'OMRI-listed',
  'targets': 'Caterpillars and worms (larvae only) — highly selective, spares most other insects',
  'health': 'Very low toxicity to people and mammals; human volunteers who ate large doses showed '
            'no adverse effects. Not a carcinogen — the Cry proteins break down in the acidic '
            'human stomach. Registered as a pesticide since 1961.',
  'environment': 'Practically non-toxic to fish, bluegill and minnows; foliage half-life ~1–4 '
                 'days.',
  'pollinators': 'Practically non-toxic to honey bees, with little to no effect on lacewings, '
                 'predatory beetles, parasitic wasps or earthworms.',
  'aquatic': 'Practically non-toxic to aquatic life.',
  'caution': 'low',
  'sources': [{'label': 'NPIC — Bacillus thuringiensis (Bt) Fact Sheet',
               'url': 'https://npic.orst.edu/factsheets/btgen.html'},
              {'label': 'EPA — Bt Reregistration Fact Sheet',
               'url': 'https://www3.epa.gov/pesticides/chem_search/reg_actions/reregistration/fs_PC-006400_24-Mar-98.pdf'}],
  'applications': 36},
 {'id': 'pyrethrins',
  'name': 'PyGanic (Pyrethrins)',
  'active': 'Pyrethrins (six botanical esters)',
  'ptype': 'Broad-spectrum insecticide',
  'origin': 'Botanical — chrysanthemum flowers',
  'omri': 'OMRI-listed',
  'targets': 'Fast knockdown of many insects — reserved for tough outbreaks (used sparingly)',
  'health': 'Low toxicity to people and mammals; skin contact can cause irritation, tingling or '
            'numbness and inhalation can irritate the airways. EPA classifies pyrethrins as ‘not '
            'likely to cause cancer’ below a threshold dose.',
  'environment': 'Breaks down fast in sunlight — half-life about 12 hours in water and soil.',
  'pollinators': 'HIGHLY TOXIC to honey bees — apply only at dusk or night when bees are not '
                 'foraging; risk is partly limited by its repellency and rapid breakdown.',
  'aquatic': 'Highly to very highly toxic to fish and aquatic invertebrates — keep well away from '
             'water.',
  'caution': 'high',
  'sources': [{'label': 'NPIC — Pyrethrins General Fact Sheet',
               'url': 'https://npic.orst.edu/factsheets/pyrethrins.html'}],
  'applications': 10},
 {'id': 'regalia',
  'name': 'Regalia (Giant Knotweed extract)',
  'active': 'Extract of Reynoutria sachalinensis',
  'ptype': 'Biofungicide / plant-defense elicitor',
  'origin': 'Botanical — giant knotweed',
  'omri': 'OMRI-listed',
  'targets': 'Fungal & bacterial diseases (powdery mildew, leaf spot) — boosts the plant’s own '
             'defenses',
  'health': 'Registered by EPA as a biopesticide in 2000; works by inducing the plant’s natural '
            'defenses rather than by direct toxicity, giving it a low-risk profile.',
  'environment': 'Reduced-risk biopesticide; no significant environmental concerns were identified '
                 'in EPA registration.',
  'pollinators': 'No significant pollinator concerns identified.',
  'aquatic': 'No significant aquatic concerns identified.',
  'caution': 'low',
  'sources': [{'label': 'EPA — Reynoutria sachalinensis (Giant Knotweed) Fact Sheet',
               'url': 'https://www3.epa.gov/pesticides/chem_search/reg_actions/registration/fs_PC-055809_01-Nov-00.pdf'}],
  'applications': 12},
 {'id': 'bacillus_subtilis',
  'name': 'Cease (Bacillus subtilis)',
  'active': 'Bacillus subtilis strain QST 713',
  'ptype': 'Biofungicide',
  'origin': 'Naturally occurring soil bacterium',
  'omri': 'OMRI-listed',
  'targets': 'Blight, gray mold, mildews and leaf spot',
  'health': 'Low toxicity to mammals; EPA found no harmful health effects expected and it is not '
            'expected to be pathogenic to humans. Its residues are exempt from tolerance on all '
            'food commodities.',
  'environment': 'A naturally widespread soil organism; handlers use standard protective '
                 'equipment.',
  'pollinators': 'No significant pollinator concerns identified.',
  'aquatic': 'No significant aquatic concerns identified.',
  'caution': 'low',
  'sources': [{'label': 'EPA — Bacillus subtilis QST 713 Fact Sheet',
               'url': 'https://www3.epa.gov/pesticides/chem_search/reg_actions/registration/fs_PC-006479_01-Jun-00.pdf'}],
  'applications': 9},
 {'id': 'kaolin',
  'name': 'Surround (Kaolin clay)',
  'active': 'Kaolin clay',
  'ptype': 'Particle-film barrier (repellent + sun protection)',
  'origin': 'Naturally occurring clay mineral',
  'omri': 'OMRI-listed',
  'targets': 'Forms a white mineral film that repels insects and shields fruit from sunburn and '
             'heat stress',
  'health': 'Long used in foods, cosmetics and medicines; based on widespread use and extensive '
            'toxicity studies EPA considers kaolin safe for humans and the environment.',
  'environment': 'A physical barrier rather than a poison — no toxic mode of action and negligible '
                 'environmental risk.',
  'pollinators': 'No toxic action; a physical film only.',
  'aquatic': 'Negligible aquatic risk.',
  'caution': 'low',
  'sources': [{'label': 'EPA — Kaolin Biopesticide Fact Sheet',
               'url': 'https://www3.epa.gov/pesticides/chem_search/reg_actions/registration/fs_PC-100104_01-Jun-99.pdf'}],
  'applications': 3},
 {'id': 'diatomaceous_earth',
  'name': 'Diatomaceous Earth',
  'active': 'Amorphous silicon dioxide (fossil diatoms)',
  'ptype': 'Physical insecticide (desiccant)',
  'origin': 'Mineral — fossilized algae',
  'omri': 'OMRI-listed (food-grade)',
  'targets': 'Crawling insects and ants — abrades and dries out the insect’s cuticle',
  'health': 'Food-grade DE is FDA ‘Generally Recognized as Safe’ and not poisonous. Key caution: '
            'wear a mask when applying — long-term inhalation of the CRYSTALLINE form is linked to '
            'silicosis and lung problems, while the amorphous food-grade form causes only mild, '
            'reversible irritation.',
  'environment': 'Practically non-toxic to fish and aquatic invertebrates and unlikely to harm '
                 'birds or wildlife, but it is not broken down by microbes or sunlight, so it '
                 'persists in the environment.',
  'pollinators': 'Non-selective on contact — kills any insect it touches, so keep it off blooms to '
                 'protect bees.',
  'aquatic': 'Practically non-toxic to aquatic life.',
  'caution': 'medium',
  'sources': [{'label': 'NPIC — Diatomaceous Earth General Fact Sheet',
               'url': 'https://npic.orst.edu/factsheets/degen.html'}],
  'applications': 5},
 {'id': 'fish_emulsion',
  'name': 'Fish Emulsion (foliar feed)',
  'active': 'Hydrolyzed fish',
  'ptype': 'Foliar fertilizer / biostimulant',
  'origin': 'Fish by-product',
  'omri': 'OMRI-listed',
  'targets': 'Nutrient foliar feed — not a pesticide (logged as a tank-mix input)',
  'health': 'A food-derived nutrient input, not a pest-control chemical; low risk.',
  'environment': 'Readily biodegradable nutrient source; avoid over-application near waterways '
                 '(nutrient load).',
  'pollinators': 'Not a pesticide.',
  'aquatic': 'Nutrient — avoid runoff to water.',
  'caution': 'info',
  'sources': [],
  'applications': 2},
 {'id': 'ocean_minerals',
  'name': 'Ocean Minerals (foliar)',
  'active': 'Sea-derived trace minerals',
  'ptype': 'Foliar micronutrient',
  'origin': 'Sea minerals',
  'omri': 'Check product listing',
  'targets': 'Trace-mineral foliar feed — not a pesticide',
  'health': 'Mineral nutrient input; low risk.',
  'environment': 'Trace-mineral foliar feed; minimal environmental concern at label rates.',
  'pollinators': 'Not a pesticide.',
  'aquatic': 'Minimal at label rates.',
  'caution': 'info',
  'sources': [],
  'applications': 1},
 {'id': 'weed_x',
  'name': 'WeedX (organic herbicide)',
  'active': 'Confirm active ingredient',
  'ptype': 'Contact herbicide (organic)',
  'origin': 'Typically fatty-acid / plant-oil based',
  'omri': 'Verify listing',
  'targets': 'Spot weed control (used once in the log)',
  'health': 'Used once. Confirm the exact product and active ingredient before spraying near food '
            'crops; organic contact herbicides are usually fatty-acid or plant-oil based.',
  'environment': 'Verify label environmental precautions before reuse.',
  'pollinators': 'Verify label.',
  'aquatic': 'Verify label.',
  'caution': 'verify',
  'sources': [],
  'applications': 1}]

PESTICIDE_LOG = [{'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '27',
  'pest': '',
  'scale': 5,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '27',
  'pest': '',
  'scale': 5,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '',
  'crop': '',
  'bed': '332',
  'pest': '',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2023-03-23',
  'crop': 'Bok Choy, red',
  'bed': '7.0',
  'pest': 'Aphids',
  'scale': 8,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '22',
  'notes': ''},
 {'date': '2023-03-23',
  'crop': 'Beans, pole',
  'bed': '9.0',
  'pest': 'Aphids',
  'scale': 8,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '29',
  'notes': ''},
 {'date': '2023-03-23',
  'crop': 'Bell pepper, red',
  'bed': '6.0',
  'pest': 'Aphids',
  'scale': 8,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '35',
  'notes': ''},
 {'date': '2023-03-24',
  'crop': 'Cabbage, green',
  'bed': '3.0',
  'pest': 'Aphids',
  'scale': 9,
  'product': 'Diatomaceous Earth',
  'chemicals': 'diatomaceous_earth',
  'dosage': '38',
  'notes': ''},
 {'date': '2023-03-27',
  'crop': 'Seedlings, eggplant',
  'bed': 'Greenhouse',
  'pest': 'Lacebugs',
  'scale': 6,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '48',
  'notes': ''},
 {'date': '2023-03-29',
  'crop': 'Seedlings, eggplant',
  'bed': 'Greenhouse',
  'pest': 'Lacebugs',
  'scale': 4,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '51',
  'notes': ''},
 {'date': '2023-03-29',
  'crop': "Squash, asst'd",
  'bed': '9, 30, 31, 42, 43',
  'pest': 'Caterpillars',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '26',
  'notes': ''},
 {'date': '2023-03-31',
  'crop': 'Seedlings, eggplant',
  'bed': 'Greenhouse',
  'pest': 'Lacebugs',
  'scale': 3,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '65',
  'notes': ''},
 {'date': '2023-03-31',
  'crop': "Squash, asst'd",
  'bed': '9, 30, 31, 42, 43',
  'pest': 'Caterpillars',
  'scale': 6,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '68',
  'notes': ''},
 {'date': '2023-04-04',
  'crop': 'Seedlings, eggplant',
  'bed': 'Greenhouse',
  'pest': 'Lacebugs',
  'scale': 4,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '86',
  'notes': ''},
 {'date': '2023-04-05',
  'crop': 'Eggplant, Asian',
  'bed': '28.0',
  'pest': 'Aphids',
  'scale': 7,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '1/2 oz ea for 2 liters',
  'notes': 'Aphids under leaf; major ant harvesting; gray&yellow flying beetle eating leaf'},
 {'date': '2023-04-14',
  'crop': 'Eggplant, Asian',
  'bed': 'Greenhouse',
  'pest': 'Leaf spot',
  'scale': 4,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '1 oz of soap & 1 oz of Regalia to one gal of water',
  'notes': 'Spots on leaf'},
 {'date': '2023-04-17',
  'crop': 'Eggplant, Asian',
  'bed': 'Greenhouse',
  'pest': 'Leaf spot',
  'scale': 3,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '114',
  'notes': ''},
 {'date': '2023-04-18',
  'crop': 'Collard Greens',
  'bed': '16.0',
  'pest': 'Caterpillars',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2023-04-18',
  'crop': 'Cabbage, green',
  'bed': '56',
  'pest': '',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2023-04-21',
  'crop': 'Eggplant, Asian',
  'bed': 'Greenhouse',
  'pest': 'Leaf spot',
  'scale': 2,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '124',
  'notes': ''},
 {'date': '2023-04-21',
  'crop': 'Eggplant, Ita',
  'bed': 'Greenhouse',
  'pest': 'Leaf spot',
  'scale': 2,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '129',
  'notes': ''},
 {'date': '2023-04-26',
  'crop': "Peppers, asst'd",
  'bed': 'Greenhouse',
  'pest': 'Whitefly',
  'scale': 3,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '134',
  'notes': ''},
 {'date': '2023-04-27',
  'crop': 'Soursop',
  'bed': 'Outside Area',
  'pest': 'Nymphs',
  'scale': 6,
  'product': 'Soap-DesX-Regalia',
  'chemicals': 'regalia,insecticidal_soap',
  'dosage': '144',
  'notes': ''},
 {'date': '2023-04-28',
  'crop': "Peppers, asst'd",
  'bed': 'Greenhouse',
  'pest': 'Whitefly',
  'scale': 2,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '148',
  'notes': ''},
 {'date': '2023-04-28',
  'crop': 'Tomato, assorted',
  'bed': '20,24,25,27',
  'pest': 'Nymphs',
  'scale': 3,
  'product': 'Soap-PyGanic-BT',
  'chemicals': 'pyrethrins,bt,insecticidal_soap',
  'dosage': '2 half gallon containers sprayed',
  'notes': ''},
 {'date': '2023-05-03',
  'crop': 'Cabbage, green',
  'bed': 'Greenhouse',
  'pest': 'Fungus',
  'scale': 4,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '73',
  'notes': ''},
 {'date': '2023-05-04',
  'crop': 'Cabbage, green',
  'bed': 'Greenhouse',
  'pest': 'Fungus',
  'scale': 4,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '162',
  'notes': ''},
 {'date': '2023-05-04',
  'crop': 'Bell pepper, yellow',
  'bed': '7.0',
  'pest': 'Whitefly',
  'scale': 3,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '115',
  'notes': ''},
 {'date': '2023-05-07',
  'crop': 'Cabbage, green',
  'bed': 'Greenhouse',
  'pest': 'Fungus',
  'scale': 3,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '167',
  'notes': ''},
 {'date': '2023-05-07',
  'crop': 'Bell pepper, yellow',
  'bed': 'Greenhouse',
  'pest': 'Whitefly',
  'scale': 5,
  'product': 'Soap-Regalia-Cease',
  'chemicals': 'regalia,bacillus_subtilis,insecticidal_soap',
  'dosage': '170',
  'notes': ''},
 {'date': '2023-05-09',
  'crop': 'Cabbage, green',
  'bed': '',
  'pest': 'Aphids',
  'scale': 3,
  'product': 'DesX-Neem-Debug',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '98',
  'notes': ''},
 {'date': '2023-05-09',
  'crop': 'Broccoli, purple',
  'bed': '',
  'pest': 'Worms',
  'scale': 2,
  'product': 'DesX-Neem-Debug',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '177',
  'notes': ''},
 {'date': '2023-05-19',
  'crop': 'NA',
  'bed': 'Front pravilion',
  'pest': 'Weeds',
  'scale': 4,
  'product': 'WeedX',
  'chemicals': 'weed_x',
  'dosage': '125',
  'notes': ''},
 {'date': '2023-05-19',
  'crop': 'NA',
  'bed': "Asst'd beds",
  'pest': 'Ants',
  'scale': 4,
  'product': 'Diatomaceous Earth',
  'chemicals': 'diatomaceous_earth',
  'dosage': '187',
  'notes': ''},
 {'date': '2023-05-30',
  'crop': 'NA',
  'bed': 'All',
  'pest': '4.0',
  'scale': None,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '191',
  'notes': ''},
 {'date': '2023-05-30',
  'crop': 'NA',
  'bed': '1,20',
  'pest': 'Ants',
  'scale': 5,
  'product': 'Diatomaceous Earth',
  'chemicals': 'diatomaceous_earth',
  'dosage': '195',
  'notes': ''},
 {'date': '2023-06-02',
  'crop': 'Peppers, thai chili',
  'bed': 'Greenhouse',
  'pest': 'Whitefly',
  'scale': 3,
  'product': 'DesX-DeBug',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '200',
  'notes': ''},
 {'date': '2023-06-02',
  'crop': 'NA',
  'bed': '15.0',
  'pest': 'Ants',
  'scale': 4,
  'product': 'Diatomaceous Earth',
  'chemicals': 'diatomaceous_earth',
  'dosage': '205',
  'notes': ''},
 {'date': '2023-06-06',
  'crop': 'Collard Greens',
  'bed': '2,3,12,13,14,18,19,21',
  'pest': 'Caterpillars',
  'scale': 2,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '208',
  'notes': ''},
 {'date': '2023-06-06',
  'crop': "Peppers, asst'd",
  'bed': '6,22',
  'pest': 'Nymphs',
  'scale': 2,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '212',
  'notes': ''},
 {'date': '2023-06-11',
  'crop': "Peppers, asst'd",
  'bed': '4,5,6,7',
  'pest': '2.0',
  'scale': None,
  'product': 'Surround',
  'chemicals': 'kaolin',
  'dosage': '217',
  'notes': ''},
 {'date': '2023-06-12',
  'crop': "Peppers, asst'd",
  'bed': '22,39',
  'pest': '2.0',
  'scale': None,
  'product': 'Surround',
  'chemicals': 'kaolin',
  'dosage': '217',
  'notes': ''},
 {'date': '2023-06-12',
  'crop': 'Eggplant, Asian',
  'bed': '7,15',
  'pest': 'Nymphs',
  'scale': 2,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '227',
  'notes': ''},
 {'date': '2023-06-12',
  'crop': 'Cabbage, green',
  'bed': '3,8,14,18,21,25',
  'pest': 'Caterpillars',
  'scale': 2,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '230',
  'notes': ''},
 {'date': '2023-06-12',
  'crop': 'Collard Greens',
  'bed': '12,2,19',
  'pest': 'Caterpillars',
  'scale': 2,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '234',
  'notes': ''},
 {'date': '2023-06-12',
  'crop': 'Broccoli, green',
  'bed': '10.0',
  'pest': 'Caterpillars',
  'scale': 2,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '235',
  'notes': ''},
 {'date': '2023-06-21',
  'crop': 'Cucumber',
  'bed': '37,14,8',
  'pest': 'Ants',
  'scale': 3,
  'product': 'Diatomaceous Earth',
  'chemicals': 'diatomaceous_earth',
  'dosage': '239',
  'notes': ''},
 {'date': '2023-06-21',
  'crop': 'All',
  'bed': 'All',
  'pest': 'General',
  'scale': 2,
  'product': 'DesX-DeBug-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '243',
  'notes': ''},
 {'date': '2023-06-26',
  'crop': 'Cucumber',
  'bed': '11,13,37',
  'pest': 'Aphids',
  'scale': 6,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '246',
  'notes': ''},
 {'date': '2023-06-26',
  'crop': 'Bell pepper, yellow',
  'bed': '6,7',
  'pest': 'Fruit Flies',
  'scale': 4,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '249',
  'notes': ''},
 {'date': '2023-06-28',
  'crop': 'Eggplant, Asian',
  'bed': '7.0',
  'pest': 'Mites',
  'scale': 8,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '254',
  'notes': ''},
 {'date': '2023-06-28',
  'crop': 'Cucumber',
  'bed': '11,13',
  'pest': 'Aphids',
  'scale': 3,
  'product': 'Soap & PyGanic',
  'chemicals': 'pyrethrins,insecticidal_soap',
  'dosage': '256',
  'notes': ''},
 {'date': '2023-06-30',
  'crop': 'All',
  'bed': 'All',
  'pest': 'General',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2023-07-04',
  'crop': "Peppers, asst'd",
  'bed': '4,5,7,18,22,39(east)',
  'pest': 'Nymphs',
  'scale': 3,
  'product': 'Surround',
  'chemicals': 'kaolin',
  'dosage': '262',
  'notes': ''},
 {'date': '2023-07-04',
  'crop': 'All',
  'bed': 'All except herbs & beans',
  'pest': 'General',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '267',
  'notes': ''},
 {'date': '2023-07-14',
  'crop': 'All',
  'bed': 'All',
  'pest': 'General',
  'scale': 3,
  'product': 'DesX-Neem-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '271',
  'notes': ''},
 {'date': '2023-07-25',
  'crop': 'Beans, pole',
  'bed': '29,30,31',
  'pest': 'Aphids',
  'scale': 2,
  'product': 'DesX-Regalia-FishEm',
  'chemicals': 'regalia,insecticidal_soap,fish_emulsion',
  'dosage': '274',
  'notes': ''},
 {'date': '2023-07-25',
  'crop': 'Okra',
  'bed': '32.0',
  'pest': 'Aphids',
  'scale': 2,
  'product': 'DesX-Regalia-FishEm',
  'chemicals': 'regalia,insecticidal_soap,fish_emulsion',
  'dosage': '42',
  'notes': ''},
 {'date': '2023-07-27',
  'crop': 'All',
  'bed': 'All except beans',
  'pest': 'General',
  'scale': 2,
  'product': 'DesX-Neem-BT',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '280',
  'notes': ''},
 {'date': '2024-11-15',
  'crop': '81 - Banana',
  'bed': '15',
  'pest': '',
  'scale': 6,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Problem addressed; Sprayed again 2 week later'},
 {'date': '2024-11-15',
  'crop': '66 - Tomato, Tiny Treats',
  'bed': '27',
  'pest': '',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed 3x more 2-3 days apart'},
 {'date': '2024-11-15',
  'crop': '43 - Pepper, Bird',
  'bed': '15',
  'pest': '',
  'scale': 6,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed 3x more 2-3 days apart'},
 {'date': '2024-11-15',
  'crop': '44 - Pepper, Chili, Red Flame',
  'bed': '15',
  'pest': '',
  'scale': 6,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed 3x more 2-3 days apart'},
 {'date': '2024-11-15',
  'crop': '45 - Pepper, Cubanelle, Nassau',
  'bed': '15',
  'pest': '',
  'scale': 6,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed 3x more 2-3 days apart'},
 {'date': '2024-11-15',
  'crop': '68 - Pepper, Scotch Bonnet',
  'bed': '15',
  'pest': '',
  'scale': 6,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed 3x more 2-3 days apart'},
 {'date': '2024-11-15',
  'crop': '69 - Pepper, Datil',
  'bed': '15',
  'pest': '',
  'scale': 6,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed 3x more 2-3 days apart'},
 {'date': '2024-11-15',
  'crop': '64 - Eggplant, Galine',
  'bed': '15',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed 3x more 2-3 days apart'},
 {'date': '2024-11-22',
  'crop': '73 - Collards, Georgia',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-22',
  'crop': '72 - Kale, Dino',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-22',
  'crop': '71 - Kale, Endor',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-22',
  'crop': '70 - Kale, Rainbow',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-22',
  'crop': '8 - Broccoli, Emerald Crown',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-22',
  'crop': '9 - Broccoli, Purple Magic',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-22',
  'crop': '51 - Swiss Chard, Bright Lights',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-22',
  'crop': '52 - Swiss Chard, Heart of Gold',
  'bed': 'All greens in ground',
  'pest': 'Worms',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Sprayed twice more 2 days apart'},
 {'date': '2024-11-29',
  'crop': '123',
  'bed': '',
  'pest': 'Whitefly',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '127'},
 {'date': '2024-11-30',
  'crop': '128',
  'bed': '',
  'pest': 'Whitefly',
  'scale': 5,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '132'},
 {'date': '2024-12-10',
  'crop': '133',
  'bed': '',
  'pest': 'Whitefly',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '138'},
 {'date': '2024-12-10',
  'crop': '59 - Turnip, Purple Top White Globe',
  'bed': '14',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '145'},
 {'date': '2024-12-10',
  'crop': '22 - Cucumber, Sashimi',
  'bed': '14',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '153'},
 {'date': '2024-12-10',
  'crop': '23 - Cucumber, Unagi',
  'bed': '14',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '147'},
 {'date': '2024-12-10',
  'crop': '47 - Radish, Nero Tondo',
  'bed': '14',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '156'},
 {'date': '2024-12-13',
  'crop': '128',
  'bed': '',
  'pest': 'Whitefly',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '172'},
 {'date': '2024-12-17',
  'crop': '128',
  'bed': '',
  'pest': 'Whitefly',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '176'},
 {'date': '2024-12-20',
  'crop': '178',
  'bed': '',
  'pest': 'Whitefly',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '183'},
 {'date': '2024-12-30',
  'crop': '66 - Tomato, Tiny Treats',
  'bed': 'All tomatoes on wall',
  'pest': 'Whitefly',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '190'},
 {'date': '2024-12-30',
  'crop': '192',
  'bed': '',
  'pest': 'Aphids',
  'scale': 6,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '197'},
 {'date': '2025-01-01',
  'crop': '66 - Tomato, Tiny Treats',
  'bed': 'All tomatoes on wall',
  'pest': 'Whitefly',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Second spraying within a week; need to prune back and air out'},
 {'date': '2025-01-03',
  'crop': '66 - Tomato, Tiny Treats',
  'bed': 'All tomatoes on wall',
  'pest': 'Whitefly',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '204'},
 {'date': '2025-01-08',
  'crop': '22 - Cucumber, Sashimi',
  'bed': '27',
  'pest': '',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': '209'},
 {'date': '2025-01-08',
  'crop': '23 - Cucumber, Unagi',
  'bed': '27',
  'pest': '',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': '214'},
 {'date': '2025-01-11',
  'crop': 'All Cucumbers',
  'bed': '27',
  'pest': '',
  'scale': 4,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-01-30',
  'crop': 'All Cucumbers',
  'bed': '27',
  'pest': '',
  'scale': 1,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-01-30',
  'crop': 'All Greens',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-01',
  'crop': 'All Cucumbers',
  'bed': '27',
  'pest': '',
  'scale': 1,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-01',
  'crop': 'All Cucumbers',
  'bed': '27',
  'pest': '',
  'scale': 1,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-08',
  'crop': 'All Radishes',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-08',
  'crop': 'All Turnips',
  'bed': '14',
  'pest': '',
  'scale': 1,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-09',
  'crop': 'All Peppers',
  'bed': '15',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-10',
  'crop': 'All Tomatoes',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-17',
  'crop': '1 - Arugula, Astro',
  'bed': '14',
  'pest': '',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-17',
  'crop': '84 - Pepper, Cayenne',
  'bed': '15',
  'pest': '',
  'scale': 3,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-02-20',
  'crop': '1 - Arugula, Astro',
  'bed': '14',
  'pest': '',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-03-31',
  'crop': 'All Greens',
  'bed': 'Brassicas',
  'pest': 'Aphids',
  'scale': 5,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-04-04',
  'crop': 'All Greens',
  'bed': 'Brassicas',
  'pest': 'Aphids',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-04-07',
  'crop': 'All Greens',
  'bed': 'Brassicas',
  'pest': 'Aphids',
  'scale': 3,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-04-23',
  'crop': 'All Kale',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-05-05',
  'crop': '20 - Collards, Cash Crop',
  'bed': '27',
  'pest': '',
  'scale': 5,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-05-12',
  'crop': 'All Eggplants',
  'bed': '14',
  'pest': '',
  'scale': 5,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-05-16',
  'crop': 'All Eggplants',
  'bed': '14',
  'pest': '',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2025-05-16',
  'crop': 'All Greens',
  'bed': '27',
  'pest': '',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': ''},
 {'date': '2026-01-18',
  'crop': '149 - Cucumbers',
  'bed': '14',
  'pest': '',
  'scale': 7,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '23'},
 {'date': '2026-01-18',
  'crop': '146 - Bok Choys',
  'bed': '14',
  'pest': '',
  'scale': 7,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Retreat on 2 days if problems persists'},
 {'date': '2026-01-18',
  'crop': '147 - Broccolis',
  'bed': '14',
  'pest': '',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Retreat on 2 days if problems persists'},
 {'date': '2026-01-18',
  'crop': '148 - Cauliflowers',
  'bed': '14',
  'pest': '',
  'scale': 2,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Retreat on 2 days if problems persists'},
 {'date': '2026-01-18',
  'crop': '151 - Mustards',
  'bed': '14',
  'pest': '',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Retreat on 2 days if problems persists'},
 {'date': '2026-01-18',
  'crop': '150 - Kales',
  'bed': '14',
  'pest': '',
  'scale': 4,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Retreat on 2 days if problems persists'},
 {'date': '2026-03-06',
  'crop': '149 - Cucumbers',
  'bed': '70',
  'pest': '',
  'scale': 5,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': 'Retreat in 2 days'},
 {'date': '2026-03-07',
  'crop': '149 - Cucumbers',
  'bed': '70',
  'pest': '',
  'scale': 5,
  'product': 'BT & Des-X',
  'chemicals': 'bt,insecticidal_soap',
  'dosage': '',
  'notes': 'Deep soil drench'},
 {'date': '2026-03-08',
  'crop': '150 - Kales',
  'bed': '14',
  'pest': '',
  'scale': 7,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '93'},
 {'date': '2026-03-08',
  'crop': '148 - Cauliflowers',
  'bed': '14',
  'pest': '',
  'scale': 7,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '97'},
 {'date': '2026-03-08',
  'crop': '154 - Collards',
  'bed': '14',
  'pest': '',
  'scale': 7,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '104'},
 {'date': '2026-03-09',
  'crop': '146 - Bok Choys',
  'bed': '14',
  'pest': '',
  'scale': 5,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '113'},
 {'date': '2026-03-09',
  'crop': '148 - Cauliflowers',
  'bed': '14',
  'pest': '',
  'scale': 5,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '119'},
 {'date': '2026-03-09',
  'crop': '147 - Broccolis',
  'bed': '14',
  'pest': '',
  'scale': 5,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '122'},
 {'date': '2026-03-09',
  'crop': '150 - Kales',
  'bed': '14',
  'pest': '',
  'scale': 5,
  'product': 'Soap & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '126'},
 {'date': '2026-05-16',
  'crop': '149 - Cucumbers',
  'bed': '14',
  'pest': '',
  'scale': 5,
  'product': 'Neem & BT',
  'chemicals': 'bt,neem',
  'dosage': '',
  'notes': '135'},
 {'date': '2026-05-16',
  'crop': '155 - Eggplants',
  'bed': '14',
  'pest': '',
  'scale': 5,
  'product': 'Ocean Minerals',
  'chemicals': 'ocean_minerals',
  'dosage': '',
  'notes': '146'},
 {'date': '2026-05-27',
  'crop': '149 - Cucumbers',
  'bed': '27',
  'pest': '',
  'scale': 4,
  'product': 'Neem-BT-DesX',
  'chemicals': 'bt,neem,insecticidal_soap',
  'dosage': '',
  'notes': 'Nataiya was shown how to spray the cucumbers with chemicals to remove worms.'},
 {'date': '2026-06-22',
  'crop': '156 - Okra',
  'bed': '169',
  'pest': '',
  'scale': 5,
  'product': 'Des-X & Neem',
  'chemicals': 'neem,insecticidal_soap',
  'dosage': '',
  'notes': '2 oz of Neem + 2 oz. of Des- X in 2 gallons of water'}]

PEST_PRESSURE = [{'pest': 'Aphids', 'applications': 14, 'avg_scale': 5.2},
 {'pest': 'Whitefly', 'applications': 14, 'avg_scale': 2.9},
 {'pest': 'Worms', 'applications': 9, 'avg_scale': 1.1},
 {'pest': 'Caterpillars', 'applications': 7, 'avg_scale': 2.9},
 {'pest': 'Nymphs', 'applications': 5, 'avg_scale': 3.2},
 {'pest': 'General', 'applications': 5, 'avg_scale': 2.6},
 {'pest': 'Lacebugs', 'applications': 4, 'avg_scale': 4.2},
 {'pest': 'Leaf spot', 'applications': 4, 'avg_scale': 2.8},
 {'pest': 'Ants', 'applications': 4, 'avg_scale': 4.0},
 {'pest': 'Fungus', 'applications': 3, 'avg_scale': 3.7},
 {'pest': 'Weeds', 'applications': 1, 'avg_scale': 4.0},
 {'pest': 'Fruit Flies', 'applications': 1, 'avg_scale': 4.0},
 {'pest': 'Mites', 'applications': 1, 'avg_scale': 8.0}]

PESTICIDE_ANNUAL = [{'year': '2023', 'applications': 55},
 {'year': '2024', 'applications': 28},
 {'year': '2025', 'applications': 24},
 {'year': '2026', 'applications': 19}]

TOTAL_DATED = 126
DATE_MIN = "2023-03-23"
DATE_MAX = "2026-06-22"
